import type { GeneratedWorkflowMeta } from "./types/workflow.types";

export function renderWorkflowScript(meta: GeneratedWorkflowMeta): string {
	return `${[
		`export const meta = ${JSON.stringify(meta, null, "\t")};`,
		"",
		"export async function run(context) {",
		"\tassertWorkflowContext(context);",
		"\tconst logger = context.logger ?? console;",
		"\tlogger.info(`precheck: ${meta.precheck.command}`);",
		"\tconst precheck = await context.commands.run(",
		"\t\tmeta.precheck.command,",
		"\t\tmeta.precheck.args,",
		'\t\t{ stage: "precheck" },',
		"\t);",
		"\tif (precheck.code !== 0) {",
		"\t\treturn { ok: false, precheck, phraseResults: [], check: undefined };",
		"\t}",
		"\tconst settled = await Promise.allSettled(",
		"\t\tmeta.phrases.map(async (phrase) => {",
		"\t\t\tlogger.info(phrase.text);",
		"\t\t\treturn context.agents.run({",
		"\t\t\t\tagent: phrase.agent,",
		"\t\t\t\tskill: phrase.skill,",
		"\t\t\t\tprompt: phrase.text,",
		"\t\t\t\tmeta,",
		"\t\t\t});",
		"\t\t}),",
		"\t);",
		"\tconst phraseResults = settled.map((result, index) =>",
		"\t\tnormalizePhraseResult(result, meta.phrases[index]),",
		"\t);",
		"\tlogger.info(`check: ${meta.check.command}`);",
		"\tconst check = await context.commands.run(",
		"\t\tmeta.check.command,",
		"\t\tmeta.check.args,",
		'\t\t{ stage: "check" },',
		"\t);",
		"\tconst phrasesOk = phraseResults.every(",
		'\t\t(result) => result.status === "fulfilled",',
		"\t);",
		"\treturn {",
		"\t\tok: precheck.code === 0 && phrasesOk && check.code === 0,",
		"\t\tprecheck,",
		"\t\tphraseResults,",
		"\t\tcheck,",
		"\t};",
		"}",
		"",
		"function normalizePhraseResult(result, phrase) {",
		'\tif (result.status === "fulfilled") {',
		'\t\treturn { phrase, status: "fulfilled", result: result.value };',
		"\t}",
		"\treturn {",
		"\t\tphrase,",
		'\t\tstatus: "rejected",',
		"\t\terror: formatError(result.reason),",
		"\t};",
		"}",
		"",
		"function assertWorkflowContext(context) {",
		'\tif (!context || typeof context !== "object") {',
		'\t\tthrow new Error("Workflow context is required");',
		"\t}",
		'\tif (!context.commands || typeof context.commands.run !== "function") {',
		'\t\tthrow new Error("Workflow context requires commands.run");',
		"\t}",
		'\tif (!context.agents || typeof context.agents.run !== "function") {',
		'\t\tthrow new Error("Workflow context requires agents.run");',
		"\t}",
		"}",
		"",
		"function formatError(error) {",
		"\tif (error instanceof Error) return error.message;",
		'\tif (typeof error === "string") return error;',
		"\ttry {",
		"\t\treturn JSON.stringify(error);",
		"\t} catch {",
		"\t\treturn String(error);",
		"\t}",
		"}",
	].join("\n")}\n`;
}
